# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSearch():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_search(self):
        # Test name: search
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://ceshiren.com/")
        # 2 | setWindowSize | 1512x882 |
        self.driver.set_window_size(1512, 882)
        # 3 | click | css=.d-icon-search |
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-search").click()
        # 4 | click | id=search-term |
        self.driver.find_element(By.ID, "search-term").click()
        # 5 | click | css=.d-icon-sliders-h |
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-sliders-h").click()
        # 6 | click | id=ember88 |
        self.driver.find_element(By.CSS_SELECTOR, ".search-query").click()
        # 7 | type | id=ember88 | selenium
        self.driver.find_element(By.CSS_SELECTOR, ".search-query").send_keys("selenium")
        # 8 | click | css=.d-button-label |
        self.driver.find_element(By.CSS_SELECTOR, ".d-button-label").click()
        # 9 | click | id=ember115 |
        # todo: 显式等待
        self.driver.find_element(By.CSS_SELECTOR, '.topic-title').click()
